services:
  api:
    image: status-order-api
    restart: always
    build: 
      context: .
      dockerfile: ./api/Dockerfile
      target: developer
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/app
    networks:
      - status-bar-network
networks:
  status-bar-network:
    driver: bridge

    